name: CI build

on:
  push:
    branches: [ "main" ]
    tags: [ "*" ]
  pull_request:
    branches: [ "main" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-windows-msvc-x86:
    name: Build for Windows (MSVC x86)
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x86

    - name: Install Ninja
      run: choco install ninja -y

    - name: Setup vcpkg (manifest mode)
      uses: lukka/run-vcpkg@v11
      with:
        vcpkgJsonGlob: vcpkg.json
        vcpkgTriplet: x86-windows-static

    - name: Compile PvZ-Portable for Windows (MSVC, x86)
      shell: pwsh
      run: |
        cmake -G "Ninja" -B build -DCMAKE_BUILD_TYPE=Release -DCONSOLE=OFF -DCMAKE_TOOLCHAIN_FILE="$env:VCPKG_ROOT/scripts/buildsystems/vcpkg.cmake" -DVCPKG_TARGET_TRIPLET=x86-windows-static
        cmake --build build

        New-Item -ItemType Directory -Force -Path dist | Out-Null
        Copy-Item build/pvz-portable.exe dist/

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: pvz-portable-windows-msvc-x86
        path: dist/

  build-windows-msys2-mingw32:
    name: Build for Windows (MSYS2 MINGW32)
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW32
        update: true
        install: >-
          base-devel
          mingw-w64-i686-cmake
          mingw-w64-i686-gcc
          mingw-w64-i686-glew
          mingw-w64-i686-libjpeg-turbo
          mingw-w64-i686-libopenmpt
          mingw-w64-i686-libogg
          mingw-w64-i686-libpng
          mingw-w64-i686-libvorbis
          mingw-w64-i686-mpg123
          mingw-w64-i686-ninja
          mingw-w64-i686-ntldd
          mingw-w64-i686-SDL2

    - name: Compile PvZ-Portable for Windows
      shell: msys2 {0}
      run: |
        mkdir build
        cmake -G Ninja -B build -DCMAKE_BUILD_TYPE=Release -DCONSOLE=ON -DCMAKE_COLOR_DIAGNOSTICS=ON -DPVZ_DEBUG=ON
        cmake --build build
        
        mkdir -p dist
        
        cp build/pvz-portable.exe dist/
        strip dist/pvz-portable.exe
        
        echo "Collecting dependencies..."
        ntldd -R dist/pvz-portable.exe \
          | grep "=>" \
          | awk '{print $3}' \
          | grep -vE '^not$' \
          | grep -ivE '[\\/]windows[\\/]' \
          | sed 's/\\/\//g' \
          | sort -u \
          | xargs -I {} cp "{}" dist/

        echo "Packed files:"
        ls -lh dist/

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: pvz-portable-windows-msys2-mingw32
        path: dist/

  build-switch:
    name: Build for Switch
    runs-on: ubuntu-latest
    container:
      image: devkitpro/devkita64:latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Compile libopenmpt for Switch
        shell: bash
        run: |
          source $DEVKITPRO/switchvars.sh
          git clone https://github.com/OpenMPT/openmpt
          cd openmpt
          make CONFIG=gcc SHARED_LIB=0 DYNLINK=0 EXAMPLES=0 OPENMPT123=0 TEST=0 PREFIX=$PORTLIBS_PREFIX install 

      - name: Compile PvZ-Portable for Switch
        shell: bash
        run: |
          source $DEVKITPRO/switchvars.sh
          mkdir build
          cd build
          aarch64-none-elf-cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS_RELEASE=-O2
          make
          aarch64-none-elf-strip pvz-portable.elf
